### ISSUE TITLE
Jukebox example not working on OSX

### ISSUE THREAD

**Issue by dfucci** [winjer/pyspotify#5]
when trying to run the example module ossaudiodev can't be found since it's not part of the python package on OSX. 
Does someone tried a workaround for this?
The error is 

Traceback (most recent call last):
  File "jukebox.py", line 30, in <module>
    from spotify.osshelper import OssController as AlsaController
  File "/Library/Python/2.6/site-packages/pyspotify-1.1-py2.6-macosx-10.6-universal.egg/spotify/osshelper.py", line 17, in <module>
    import ossaudiodev
ImportError: No module named ossaudiodev

**Comment by ghost** [comment]
Same problem... You found a fix?

**Comment by dfucci** [comment]
Not much.
I've upgraded to Lion and upgraded XCode and now that'w what I get
lipo: can't open input file: /var/tmp//ccGoy5Qg.out (No such file or directory)
error: command 'llvm-gcc-4.2' failed with exit status 1

Still haven't found a good python wrapper for libspotify :(

**Comment by tbarbugli** [comment]
@slacko try to prepend this to the install cmd: env ARCHFLAGS="-arch i386 -arch x86_64"
